using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
//database structure
//incidents -> accounts -> contacts
//incident -> account, 1=>M,
//account -> contact , 1=> M Incident, incident name - primary key, autogenerated, string
//Account, Name - > unique string field

namespace TestTask3
{
	//these model could be divided into different files if they were more complex

	public class Incident
	{
		[Key]
		public string Name { get; set; }
		public List<Account> Accounts { get; set; }
	}
	public class Account
	{
		[Key]
		public string Name { get; set; }
		public List<Contact> Contacts { get; set; }
	}
	public class Contact
	{
		[Key]
		public string Email { get; set; }
		public string AccountName { get; set; }
		public string First_Name { get; set; }
		public string Last_Name { get; set; }
	}
}
